ruby '2.7.1'
source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-redirect-from'
gem 'bootstrap-sass'
gem 'jekyll-bootstrap-sass'
gem 'octopress-paginate', git: 'https://github.com/concur/paginate.git', branch: 'deprecation-warning-fix'
gem 'html-proofer'
gem 'sass'