@startuml hotel-modify

participant "User" as user

participant ConcurHotel as cHotel #Lightcyan
participant "CHSSupplier" as supply #LightBlue

activate cHotel
user -> cHotel: Check if hotel booking can be modified
cHotel -> cHotel:  Determine if hotel booking supplier supports modify\nand booking has `isModifiable` true
alt modify not supported
     cHotel --> user: Notify user that hotel cannot be modified
end
cHotel --> user: Present modify option
deactivate cHotel

user -> cHotel++: Provide new dates for hotel booking
cHotel -> supply++: Reshop (rate-details) for new dates\nfor booked hotel and rate plan
supply --> cHotel--: Return new rate details
cHotel --> user--: Present new rate details


user -> cHotel++: Review and confirm new rate details

cHotel -> supply++: Modify hotel booking with new rate plan id and dates
supply --> cHotel--: Return confirmation of modified hotel booking

cHotel -> cHotel: Validate that the returned dates match the new dates
alt Dates do not match
  cHotel -->user: Notify user that hotel booking\nwas not modified
else
  cHotel -->user: Notify user that hotel booking\nhas been modified
end
deactivate cHotel


@enduml
