@startuml

| User |
start
:Selects Hotel marked as "On Request" and clicks "Book";
| Hotel |
:Creates Hotel Booking in Tripstore with TSM status "Initiated";
| Tripstore |
:updates Trip Document;
| Hotel |
: Sends request to Supplier to book Hotel;
| Supplier |
: Captures request and acknowledges with confirmation number;
| Hotel |
: Updates Hotel Booking in Tripstore with confirmation number and status "Pending";
| Tripstore |
:updates Trip Document;
| Hotel |
: Updates TSM status as "Reserved";
| TSM |
:Transit booking state to "Reserved";
:Calculate Trip State;
:Updates states in Tripstore;
| Tripstore |
:updates Trip Document;
| Hotel |
:Redirects user to Finalize page;
| User |
:Finalizes Trip or adds more bookings;
end
@enduml