@startuml hotel-cancel

participant "GDS" as gds #LightYellow
participant Concur as concur #Lightcyan
participant "CHSSupplier" as supply #LightBlue

== GDS add external booking ==
gds -> concur++: GDS PNR Changed
concur -> supply++: Read reservation \n<b>/hotels/reservation/read</b>
supply --> concur--: Return confirmation numbers
concur --> concur--: Update storage
concur --> gds--: Confirm change

@enduml
